image: mcr.microsoft.com/dotnet/sdk:5.0-focal

include:
  - project: "gitlab/ci-templates"
    file: "/autodevops-ci.yml"

stages:
  - prebuild
  - build
  - deploy

version:
  extends: .version
  stage: prebuild
  tags:
    - docker

warmer:
  extends: .kanikocache
  stage: prebuild
  tags:
    - docker

build:
  extends: .kanikobuild
  tags:
    - docker
  stage: build
  dependencies:
    - version

deploy:
  stage: deploy
  script:
    - dotnet pack -c Release -o $PWD/nuget
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "$PWD/nuget/*.nupkg" --source gitlab
  only:
    - master
    - tags